### PR TITLE
Add link for Windows 7

### PR DESCRIPTION
**Pull request by megafon929**
Add link for Windows 7.
Since the latest Python doesn't work on Windows 7, I suggest leaving links to the latest version

### CODE REVIEW

**Comment by chaosmaster** [comment]
Maybe just link to here: https://www.python.org/downloads/windows/

it lists all the versions, and what windows version they are compatible with.

**Comment by megafon929** [comment]
People are blind to this, it is better to specify direct links. I have already indicated links to the latest working version under Windows 7 everywhere

**Comment by chaosmaster** [comment]
Versions may change and readme would need to be updated as a result.
Rather have a link to a generic page.
Maybe add a comment, to make sure to select the appropriate version for your OS?

**Comment by megafon929** [comment]
I'm using Windows 10. I helped people restore their devices. A lot of people with Windows 7. Windows 7 do not work with the latest Python, but everything works fine according to my links

**Comment by chaosmaster** [comment]
I understand that, this link: https://www.python.org/downloads/windows/
explicitly says which versions of python support windows 7 (and even windows XP)
so just refer to that page, and remind people to select the proper version for their Windows.

> Note that Python 3.8.7 cannot be used on Windows XP or earlier.
> Note that Python 3.9.1 cannot be used on Windows 7 or earlier.

**Comment by chaosmaster** [comment]
You didn't have to close this, just update the PR...

**Comment by megafon929** [comment]
Yes, I already announced it, where it was possible.

**Pull request closed without merging**
